---
# Configuration file for MegaLinter
# See all available variables at
# https://megalinter.io/ and in linters documentation

APPLY_FIXES: all
PARALLEL: false
SHOW_ELAPSED_TIME: false # Show elapsed time at the end of MegaLinter run
FILEIO_REPORTER: false # Generate file.io report
GITHUB_STATUS_REPORTER: true # Generate GitHub status report
IGNORE_GENERATED_FILES: true # Ignore generated files
JAVASCRIPT_DEFAULT_STYLE: prettier # Default style for JavaScript
PRINT_ALPACA: false # Print Alpaca logo in console
SARIF_REPORTER: true # Generate SARIF report
SHOW_SKIPPED_LINTERS: false # Show skipped linters in MegaLinter log

DISABLE_LINTERS:
  - REPOSITORY_DEVSKIM
  - REPOSITORY_GRYPE
  - SPELL_CSPELL
  - PHP_PSALM
  - COPYPASTE_JSCPD

TRIVY_SEVERITY: CRITICAL,HIGH
PHP_PHPSTAN_CONFIG_FILE: phpstan.neon
FILTER_REGEX_EXCLUDE: >
  (node_modules|vendor|\.automation/test|docs/json-schemas|\.github/workflows)
